name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-20.04  # ubuntu-latest
    container:
      image: ghcr.io/day8/chrome-latest:2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      # - run: npm run ci
      # - name: npm install
      #   run: 'npm install'
      # - name: build app
      #   run: pwd && mkdir -p resources/public/js/compiled/ && ls -lah resources/public/js/compiled/ && touch resources/public/js/compiled/app.js && chmod 777 resources/public/js/compiled/app.js && npm run release
      - name: run tests
        run: |
          nohup npm run watch &
          sleep 180
          karma start --single-run
